package com.wondergroup.example.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 2017-11-22 11:11:06 by Hibernate Tools 3.4.0.CR1

/**
 * SysGoodsdetailTable generated by hbm2java
 */
@Entity
@Table(name="sys_goodsdetail_table")
public class SysGoodsdetailTable implements java.io.Serializable {

	/**
	  *@Fields serialVersionUID:（用一句话描述这个变量表示什么）
	  */
	
	private static final long serialVersionUID = 1L;
	private String id;
	private String goodsId;
	private String goodsDetail;
	private String goodsImgPath;

	public SysGoodsdetailTable() {
	}

	public SysGoodsdetailTable(String id, String goodsId) {
		this.id = id;
		this.goodsId = goodsId;
	}

	public SysGoodsdetailTable(String id, String goodsId, String goodsDetail,
			String goodsImgPath) {
		this.id = id;
		this.goodsId = goodsId;
		this.goodsDetail = goodsDetail;
		this.goodsImgPath = goodsImgPath;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getGoodsDetail() {
		return this.goodsDetail;
	}

	public void setGoodsDetail(String goodsDetail) {
		this.goodsDetail = goodsDetail;
	}

	public String getGoodsImgPath() {
		return this.goodsImgPath;
	}

	public void setGoodsImgPath(String goodsImgPath) {
		this.goodsImgPath = goodsImgPath;
	}

}
